// <auto-generated />

using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;

namespace CinemaManagementSystem.Infrastructure.Common.Persistence.Migrations
{
    [DbContext(typeof(CinemaManagementSystemDbContext))]
    [Migration("20200928141252_InitialDomainTables")]
    partial class InitialDomainTables
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CinemaManagementSystem.Domain.Cinemas.Models.Cinemas.Cinema", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cinemas");
                });

            modelBuilder.Entity("CinemaManagementSystem.Domain.Cinemas.Models.Cinemas.Projection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AvailableSeatsCount")
                        .HasColumnType("int");

                    b.Property<int?>("RoomId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.ToTable("Projections");
                });

            modelBuilder.Entity("CinemaManagementSystem.Domain.Cinemas.Models.Cinemas.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CinemaId")
                        .HasColumnType("int");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<short>("Rows")
                        .HasColumnType("smallint");

                    b.Property<short>("SeatsPerRow")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("CinemaId");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("CinemaManagementSystem.Domain.Cinemas.Models.Cinemas.Projection", b =>
                {
                    b.HasOne("CinemaManagementSystem.Domain.Cinemas.Models.Cinemas.Room", null)
                        .WithMany("Projections")
                        .HasForeignKey("RoomId");

                    b.OwnsOne("CinemaManagementSystem.Domain.Cinemas.Models.Cinemas.Movie", "Movie", b1 =>
                        {
                            b1.Property<int>("ProjectionId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<short>("DurationMinutes")
                                .HasColumnType("smallint");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("ProjectionId");

                            b1.ToTable("Projections");

                            b1.WithOwner()
                                .HasForeignKey("ProjectionId");
                        });
                });

            modelBuilder.Entity("CinemaManagementSystem.Domain.Cinemas.Models.Cinemas.Room", b =>
                {
                    b.HasOne("CinemaManagementSystem.Domain.Cinemas.Models.Cinemas.Cinema", null)
                        .WithMany("Rooms")
                        .HasForeignKey("CinemaId");
                });
#pragma warning restore 612, 618
        }
    }
}
